from pathlib import Path
import shutil
import subprocess

def compile_with_latexmk(tex_path: Path) -> None:
    """Compile LaTeX file to PDF using latexmk."""

    latexmk = shutil.which("latexmk")
    if not latexmk:
        raise FileNotFoundError("latexmk not found in PATH. Please install it to compile LaTeX documents.")
    cwd = tex_path.parent
    args = [latexmk, "--pdf", tex_path.name]
    subprocess.run(args, cwd=cwd, check=True)

def clean_auxiliary_files(tex_path: Path) -> None:
    """Clean auxiliary files generated by LaTeX compilation."""

    latexmk = shutil.which("latexmk")
    if not latexmk:
        raise FileNotFoundError("latexmk not found in PATH. Please install it to clean LaTeX auxiliary files.")
    cwd = tex_path.parent
    args = [latexmk, "-c", tex_path.name]
    subprocess.run(args, cwd=cwd, check=True)